name: Stage deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - stage*
  pull_request:
    types:
      - closed
    branches:
      - stage*

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: 🔨 Build Project
        run: |
          cd full-version            
          yarn
          yarn build-stage

      - name: 📂 Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          # ARGS: "-rltgoDzvO --delete f"
          SOURCE: "full-version/dist/"
          REMOTE_HOST: 192.34.62.123
          REMOTE_USER: ableproadmin
          TARGET: public_html/react/stage
          EXCLUDE: "/full-version/node_modules/"
